# Generated by Django 5.2.6 on 2025-10-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='date',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='quantity',
            field=models.CharField(choices=[('250g', '250g'), ('500g', '500g'), ('1000g', '1000g')], max_length=10),
        ),
    ]
